name: main

on: 
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node
      uses: actions/setup-node@v2
      with: 
        node-version: '17.3.0'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run Test
      run: npm test

  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install
        run: npm ci

      - name: site
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.ACTION_TOKEN }}
          publish_dir: ./build
          force_orphan: true
