name: main

on: 
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup node
      uses: actions@v1
      with: 
        node-version: '17.3.0'

    - name: Install dependencies
      run: npm install -g serve

    - name: Run build
      uses: |
        npm run build 
        serve -s build
