name: main

on: 
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with: 
        node-version: '17.3.0'

    - name: Install dependencies
      run: npm install

    - name: Run build
      uses: npm run build 
    - uses: serve -s build
