name: main

on: 
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node
      uses: actions/setup-node@v2
      with: 
        node-version: '17.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm install -g serve

    - name: Run build
      run: npm ci
    - run: npm run build 
    - run: npm test
    - run: serve -s build
