name: main

on: 
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node
      uses: actions/setup-node@v2
      with: 
        node-version: '17.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run Test
      run: npm test

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node
      uses: actions/setup-node@v2
      with: 
        node-version: '17.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm install -g serve

    - name: Run Build
      run: npm run build 
